### ISSUE TITLE
lowercase issue

### ISSUE THREAD

**Issue by PsykonoyaK** [maxdow/angularjs-requirejs-seed#3]
Hi, 
pretty cool project. I was looking for a similar project, using AngularJS + RequireJS. It's done.
I had a little issue at the first loading of the index.html
You have to fix "app.js", at line 6
"Controllers/Controllers" to "Controllers/controllers"

Thanks.
Tony

**Comment by maxdow** [comment]
Hi, thanks for writing this issue. I updated the repo
